"""Composable building blocks for the shopping-agent implementation."""

from .actions import (
    ACTION_NAMES,
    ActionObservation,
    ActionValidationError,
    PendingTask,
    PlannedAction,
    TrajectoryEntry,
    parse_planned_action,
)
from .catalog import (
    CatalogRepository,
    CategoryResolution,
    ProductRecord,
    RetrievedProduct,
    normalize_category,
)
from .config import AgentConfig
from .model import (
    BackendFailure,
    BackendJSONError,
    BackendRequestError,
    BackendResponse,
    BackendValidationError,
    DeepSeekAPIBackend,
    DeepSeekBackend,
    LocalModelBackend,
    LocalOpenAIBackend,
    ModelBackendError,
    ModelCompletionResult,
    TieredModelClient,
    TokenUsage,
)
from .orchestrator import ActionOrchestrator, OrchestratorResult
from .planner import (
    ActionPlanner,
    DeterministicActionPlanner,
    ModelActionPlanner,
    PlannerContext,
    PlannerResult,
    ScriptedActionPlanner,
)
from .policy import (
    CATEGORY_RECALL_MAX_LIMIT,
    CATEGORY_RECALL_MIN_LIMIT,
    CATEGORY_RECALL_SMALL_LIMIT,
    CandidateGate,
    CandidateGateDecision,
    ClarificationPolicy,
    IntentRouter,
    RouteDecision,
    adaptive_category_budget,
    category_recall_budget,
    category_recall_ratio,
)
from .qwen_reranker import (
    BACKEND_NAME as QWEN_RERANKER_BACKEND_NAME,
)
from .qwen_reranker import (
    SHOPPING_RELEVANCE_INSTRUCTION,
    QwenCrossEncoderReranker,
)
from .semantic_ranking import LLMSemanticRanker, SemanticRankingResult
from .state import (
    ALLOWED_ATTRIBUTES,
    CandidateStats,
    Constraint,
    ConstraintMutation,
    IntentUpdate,
    RuntimeContext,
    SessionState,
    SessionStore,
    StateReducer,
    bind_clarification_answer,
    parse_intent_update,
)
from .tools import ShoppingToolbox

__all__ = [
    "ACTION_NAMES",
    "ALLOWED_ATTRIBUTES",
    "CATEGORY_RECALL_MAX_LIMIT",
    "CATEGORY_RECALL_MIN_LIMIT",
    "CATEGORY_RECALL_SMALL_LIMIT",
    "QWEN_RERANKER_BACKEND_NAME",
    "SHOPPING_RELEVANCE_INSTRUCTION",
    "ActionObservation",
    "ActionOrchestrator",
    "ActionPlanner",
    "ActionValidationError",
    "AgentConfig",
    "BackendFailure",
    "BackendJSONError",
    "BackendRequestError",
    "BackendResponse",
    "BackendValidationError",
    "CandidateGate",
    "CandidateGateDecision",
    "CandidateStats",
    "CatalogRepository",
    "CategoryResolution",
    "ClarificationPolicy",
    "Constraint",
    "ConstraintMutation",
    "DeepSeekAPIBackend",
    "DeepSeekBackend",
    "DeterministicActionPlanner",
    "IntentRouter",
    "IntentUpdate",
    "LLMSemanticRanker",
    "LocalModelBackend",
    "LocalOpenAIBackend",
    "ModelActionPlanner",
    "ModelBackendError",
    "ModelCompletionResult",
    "OrchestratorResult",
    "PendingTask",
    "PlannedAction",
    "PlannerContext",
    "PlannerResult",
    "ProductRecord",
    "QwenCrossEncoderReranker",
    "RetrievedProduct",
    "RouteDecision",
    "RuntimeContext",
    "ScriptedActionPlanner",
    "SemanticRankingResult",
    "SessionState",
    "SessionStore",
    "ShoppingToolbox",
    "StateReducer",
    "TieredModelClient",
    "TokenUsage",
    "TrajectoryEntry",
    "adaptive_category_budget",
    "bind_clarification_answer",
    "category_recall_budget",
    "category_recall_ratio",
    "normalize_category",
    "parse_intent_update",
    "parse_planned_action",
]
