"""Composable building blocks for the shopping-agent implementation."""

from .catalog import (
    CategoryResolution,
    CatalogRepository,
    ProductRecord,
    RetrievedProduct,
    normalize_category,
)
from .config import AgentConfig
from .model import (
    BackendFailure,
    BackendJSONError,
    BackendRequestError,
    BackendResponse,
    BackendValidationError,
    DeepSeekAPIBackend,
    DeepSeekBackend,
    LocalModelBackend,
    LocalOpenAIBackend,
    ModelCompletionResult,
    ModelBackendError,
    TieredModelClient,
    TokenUsage,
)
from .semantic_ranking import LLMSemanticRanker, SemanticRankingResult
from .qwen_reranker import (
    BACKEND_NAME as QWEN_RERANKER_BACKEND_NAME,
    QwenCrossEncoderReranker,
    SHOPPING_RELEVANCE_INSTRUCTION,
)
from .state import (
    ALLOWED_ATTRIBUTES,
    CandidateStats,
    Constraint,
    ConstraintMutation,
    IntentUpdate,
    RuntimeContext,
    SessionState,
    SessionStore,
    StateReducer,
    parse_intent_update,
)
from .policy import (
    CATEGORY_RECALL_MAX_LIMIT,
    CATEGORY_RECALL_MIN_LIMIT,
    CATEGORY_RECALL_SMALL_LIMIT,
    CandidateGate,
    CandidateGateDecision,
    ClarificationPolicy,
    IntentRouter,
    RouteDecision,
    adaptive_category_budget,
    category_recall_budget,
    category_recall_ratio,
)

__all__ = [
    "AgentConfig",
    "ALLOWED_ATTRIBUTES",
    "BackendFailure",
    "BackendJSONError",
    "BackendRequestError",
    "BackendResponse",
    "BackendValidationError",
    "CATEGORY_RECALL_MAX_LIMIT",
    "CATEGORY_RECALL_MIN_LIMIT",
    "CATEGORY_RECALL_SMALL_LIMIT",
    "CandidateGate",
    "CandidateGateDecision",
    "CandidateStats",
    "CatalogRepository",
    "CategoryResolution",
    "ClarificationPolicy",
    "Constraint",
    "ConstraintMutation",
    "DeepSeekAPIBackend",
    "DeepSeekBackend",
    "LocalModelBackend",
    "LocalOpenAIBackend",
    "LLMSemanticRanker",
    "QWEN_RERANKER_BACKEND_NAME",
    "QwenCrossEncoderReranker",
    "SHOPPING_RELEVANCE_INSTRUCTION",
    "IntentRouter",
    "IntentUpdate",
    "ModelCompletionResult",
    "ModelBackendError",
    "SemanticRankingResult",
    "ProductRecord",
    "RetrievedProduct",
    "RouteDecision",
    "adaptive_category_budget",
    "category_recall_budget",
    "category_recall_ratio",
    "normalize_category",
    "RuntimeContext",
    "SessionState",
    "SessionStore",
    "StateReducer",
    "TieredModelClient",
    "TokenUsage",
    "parse_intent_update",
]
